language: node_js
node_js: node
cache:
  npm: false
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
- cp icons/* _book/gitbook/images
deploy:
  local_dir: _book
  provider: pages:git
  edge: true
  skip_cleanup: true
  committer_from_gh: true
  fqdn: wifi.dortania.ml
  keep_history: true
  verbose: true
  on:
    branch: master
  commit_message: "%{git_commit_msg}"
  token:
    secure: dT1hd2GiNP8cq80OOX8GJ5lH3DYrwjmdr353jXoaduro4lgmTPw7absITpz8hdEJj6m2N1QC/QxyZHhjmJryfpW6VdTKmBF6pSZ1aDlMAjTs3m+cnfVjOKaK3ozqBBm6eHfkC+QO3aO3sjolqKHJ9Erflvsa5kMQiKgGANFy8reW8smmu9LZ8DmieMd+0D9CDtvBVjBrI1WVyTbmnlmQWypx59erQwImCIDevI5DUJfqchSBFY6WfN8IHOU4LHUoTv4t5H85ORNb+lbSKacMcxF9ZUjgH+zD43CxEgWFRpBksEm16l81vp1mRuLJ1w8apiX7xUfDMvC1Y7VtOo7PFSTOwmM9334UXf3L91/Abd9RqAWOTO5SEZHYSVaqIMRHNdfwqzFTj1eeGs8TutDrKj26iYHHUV0cEzI3HA18QOn+8TKwlunRX8lKXI4L6NuLUI4Vm73VnfpUe0FoY4n+jcCVl32LVM9K9TLTmYzZL5YgUG5lROJ/E1XeRpuhaysi3gFtFsEF6N8WR+c5b94KANX9cJf8cnyg33H9yETxw/JkxXhKMh9QoovaEdRDc+2UpysU1+zb2nECnu9+WsEpjvAXUXzjutIZRmt6h1JBrf+4/3mMPE45wk1rugdgM2O1pegji/pD5P/asx2XMOuA342lgUXmApFLiipVPD3csPk=
